### ISSUE TITLE
support needed

### ISSUE THREAD

**Issue by bluetulip89** [hansinahuja/Voice-Controlled-Robotic-Arm#1]
Thanks for the nice project. 

Can you please add some few lines in README regarding the links and procedure of setting IFTTT and voice assistant. It will be helpful for the newbies who have a look at your code and to begin with.

**Comment by hansinahuja** [comment]
Hey, 

Luckily there's a ton of community support for setting up Google assistant with IFTTT. You might find these links to be helpful:

https://www.hackster.io/igorF2/wi-fi-voice-controlled-robot-using-google-assistant-79802c
http://rootsaid.com/google-assistant-robot/
